# Generated by Django 6.0.6 on 2026-06-21 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Álbum')),
                ('artista', models.CharField(max_length=200, verbose_name='Artista / Banda')),
                ('ano_edicion', models.IntegerField(verbose_name='Año de Edición')),
                ('sello_discografico', models.CharField(max_length=100, verbose_name='Sello Discográfico')),
                ('formato', models.CharField(choices=[('VINILO', 'Vinilo'), ('CD', 'CD'), ('CASSETTE', 'Cassette'), ('DIGITAL', 'Digital')], default='CD', max_length=20)),
                ('resena', models.TextField(blank=True, verbose_name='Reseña o Comentarios')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Imagen de Portada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
        ),
    ]
